### ISSUE TITLE
Large collections timeout in web UI

### ISSUE THREAD

**Issue by GeoffFroh** [densho/ddr-local#159]
Large collections (e.g., ddr-hmwf-1, ddr-densho-266) timeout with a generic 502 and/or 504 gateway timeout error when attempting to reach the main collection page (e.g., http://192.168.56.101/ui/ddr-hmwf-1) in the web ui. Usually, the page will resolve after 5 to 6 attempts; but sometimes not.

* Behavior has been observed repeatably against the NFS-based storage at Densho HQ from multiple VMs
* Object and file pages in the affected collections are accessible directly

**Comment by gjost** [comment]
This should not be a problem now.  Collection status is updated in the background, as are all write operations.
