### ISSUE TITLE
"no store present" when running ddr-export.py

### ISSUE THREAD

**Issue by gjost** [densho/ddr-local#181]
First, it seems like the behavior for setting the `docstore` base may have changed? I wanted to set up dragontail so that it was using a set of test repos on the VM itself  instead of pointing at the gold repos on the qumulo. 

I used the form at `/storage` to set the base repo dir -- in this case, `/media/hdd2/ddr` -- I could see that a symlink was created in `/var/www/media`; but rather than `/var/www/media/base` as in prior versions of `ddr-local`, it created `/var/www/media/ddr --> /media/hdd2/ddr`. The old symlink `/var/www/media/base` was still present and pointing at `/media/qnfs/kinkura/gold`.

From the webui, I was definitely seeing the local storage -- i.e., the collections list only showed the two test repos on my local VM. So I manually deleted the `/var/www/media/base` symlink.

Everything from the webui seemed to work fine. I could create new objects (ID service fix is working!), edit metadata, add binaries and sync. 

However, when I tried to run the `ddr-export.py` script, I got an error that, "no store present." When I manually created the symlink `/var/www/media/base --> /media/hdd2/ddr`, the script worked as expected.

**Update:** Second issue moved to https://github.com/densho/ddr-local/issues/182

**Comment by gjost** [comment]
Pretty much everything  that happens in `/storage/` happens in the `storage` app (`ddr-local/ddrlocal/storage`), which was not modified between master and batch-edit.
There are a few calls to `DDR.commands`:
```
commands.storage_status
commands.mount
commands.unmount
```
and a couple to `DDR.storage`, but none of that code changed either.
* https://github.com/densho/ddr-local/compare/master...batch-edit
* https://github.com/densho/ddr-cmdln/compare/master...batch-edit

The storage app takes the path you enter in the form and uses it as the target of a symlink from `settings.MEDIA_BASE`.  Nothing is appended to the path.

`MEDIA_BASE` is set in `/etc/ddr/ddr.cfg`, which is copied from `ddr-local/debian/conf/ddr.cfg`.
This *is* new -- `MEDIA_BASE` used to be just `MEDIA_ROOT` plus `base/`.
This was added so that `ddr-cmdln` would have access to this setting.
FWIW, I looked in my `/var/www/media/` and found both the `base` and `ddr` symlinks.

**Comment by gjost** [comment]
Was this the error that you saw: `("Could not load repo_models. No Store mounted, no 'ddr' repository, or no valid repo_models in 'ddr'.`
If so, it indicates that the `ddr` repo was not present or did not contain the `repo_models` directory.
If the `ddr` repo is there but `repo_models` is absent, check that the `ddr` repo is on the `batch-edit` branch.

**Comment by GeoffFroh** [comment]
Just double-checked, and yes, the ddr repo was present and on the batch-edit branch. FWIW, the error went away after I manually created the symlink /var/www/media/base --> /media/hdd2/ddr.

**Comment by gjost** [comment]
Looks like the problem was the `repo_models_path` setting in `/etc/ddr/ddr.cfg`.  This is currently a subdir of `media_base` but I guess I changed it so it doesn't have to be.  I still had the `/var/www/media/base` symlink laying around my dev VM so the old setting still worked when it should not have.
