### ISSUE TITLE
make install script points at old servername for custom ES package

### ISSUE THREAD

**Issue by GeoffFroh** [densho/ddr-local#193]
The makefile install script still points at tank.densho.org to download the custom version (1.0.1) of the Elasticsearch debian package.

**Comment by GeoffFroh** [comment]
And package source does not exist on warhorse. Not certain that nginx is configured to serve install packages.

**Comment by gjost** [comment]
I set up the directories on `dori` and arranged for all the necessary files to be present.
Also updated the package server setting in `Makefile` in both `develop` and `master` branches.
