### ISSUE TITLE
solitary topics being munged on save

### ISSUE THREAD

**Issue by densho** [densho/ddr-local#220]
cameron_johnson, 2107-12-12 15:52

> Error ID:[EID-2017-12-12-1-densho320]
> Status: [ToDo]
> Local Machine: [Pahto]
> Full Collection+Object ID Error Path: [ddr-densho-320]
> Time and Date of Error: [13:30]
> Brief Error Description: [Topics entered into DDR were appearing munged, being truncated after the first segement of the full topic (ending right before the first colon). After some testing this afternoon, a workaround was found by allowing the topic -when autocompleted- to autopopulate the proceeding blank topic input box, resulting in two identical full topic entries that yielded one single unmunged topic in the object-level metadata page in DDR.]
> Steps to Replicate Error:[Error is no longer occurring in newly created objects as of 15:35, however, the  remaining munged items persist only until they are "saved" over again. Upon saving today, they are unmunged and require no duplicated topic entries.]

**Comment by gjost** [comment]
Tried with the following topics:
- Arts and literature [40]
- Arts and literature: Literary arts [181]
- Arts and literature: Literary arts: Essays [240]
Have not observed the described behavior.

Description above also suggests that the problem is no longer occurring.
