### ISSUE TITLE
ui: make some additional entity attributes "inheritable" from parent

### ISSUE THREAD

**Issue by GeoffFroh** [densho/ddr-local#241]
Currently,  the webui user can set the values for `entity.public`, `entity.status` and `entity.rights`  from the `entity`'s parent `collection`. See: https://github.com/densho/ddr-local/issues/66

This behavior should be added for the following:

`collection.contributor` --> `entity.contributor`
`collection.prefercite` --> `entity.credit`

QUESTION: will this fit implementation for the existing "inheritance" behavior since the `prefercite` attribute name is different than `credit`?

**Comment by GeoffFroh** [comment]
Connected to: https://github.com/densho/ddr-public/milestone/10

**Comment by gjost** [comment]
Should be fixed as of commit 8807a3b.
