### ISSUE TITLE
Update object list when entity is deleted in WebUI

### ISSUE THREAD

**Issue by sarabeckman** [densho/ddr-local#242]
When an object/entity is deleted successfully in the WebUI, the object list isn't automatically updated to reflect this. 

The object/entity list did update to reflect the deletion after syncing the collection. However, it would be less confusing to the archivist working with the collection if the list in the WebUI automatically updates when the deletion finishes successfully.

**Comment by gjost** [comment]
Should be fixed as of ddr-cmdln commit f71203c6f4 and ddr-local commit e05b841014.
