### ISSUE TITLE
Make Object Signature button not working

### ISSUE THREAD

**Issue by sarabeckman** [densho/ddr-local#244]
Using webUI with my local VM version 2.6.9 

I tried to generate new object signatures in ddr-csujad-29. An "In Progress" message popped up and then "Succeed" but nothing was written to the entity.json file.

**Comment by GeoffFroh** [comment]
Try testing `ddr-signatures` command on the repo

**Comment by GeoffFroh** [comment]
Also found behavior in a `ddr-testing` collection

**Comment by sarabeckman** [comment]
> Try testing `ddr-signatures` command on the repo

I tested `ddr-signatures` on `ddr-csujad-29` and it worked. 

As a note - when you run `ddr-signatures` on objects with no mezzanine files but it does have transcript files - the transcript file is chosen as the signature.

**Comment by gjost** [comment]
Note: "Make collection signature" button *does* work.

**Comment by gjost** [comment]
Fixed in commit abfb2eb.  Refactored this to be more generic and flexible.
