### ISSUE TITLE
Admin segment titles being used in place of Object titles in DDREditor UI

### ISSUE THREAD

**Issue by pkikawa** [densho/ddr-local#248]
Admin titles will replace object titles in the objects list for a collection
![funkysegments](https://user-images.githubusercontent.com/28398832/54646340-fedebb80-4a5b-11e9-80ed-ca937e4311ff.PNG)

original object .json is intact.
[Objects _ ddr-testing-40148 _ Workbench _ DDR.html.txt](https://github.com/densho/ddr-local/files/2985797/Objects._.ddr-testing-40148._.Workbench._.DDR.html.txt)

**Comment by GeoffFroh** [comment]
Related to https://github.com/densho/ddr-cmdln/issues/138
