### ISSUE TITLE
Deleting transcripts results in failure message.

### ISSUE THREAD

**Issue by pkikawa** [densho/ddr-local#250]
deleting transcripts results in a failure message (with various levels of useful details) - files are being deleted but the changes are not being staged for commit. seeing this behavior on master 2.7.1 and dev 2.7.1a
[transcriptdeletefailure.txt](https://github.com/densho/ddr-local/files/3009903/transcriptdeletefailure.txt)

**Comment by gjost** [comment]
See https://github.com/densho/ddr-cmdln/issues/129
