### ISSUE TITLE
cannot delete child entities

### ISSUE THREAD

**Issue by pkikawa** [densho/ddr-local#251]
found on version Dana's local 2.7.1MA, deleting child entity resulted in TypeError. confirmed on PYK's vm as well

[local.log](https://github.com/densho/ddr-local/files/3030588/local.log)
[TypeError at _ui_entity_ddr-densho-1000-449-18_delete_.txt](https://github.com/densho/ddr-local/files/3030589/TypeError.at._ui_entity_ddr-densho-1000-449-18_delete_.txt)

**Comment by GeoffFroh** [comment]
Not actually a defect -- the functionality to delete child entities was discussed, but not implemented.

**Comment by GeoffFroh** [comment]
The delete function for a child entity would need to remove any files attached to the entity, then update the parent entity's `children` list to remove the reference to the child entity, and finally delete the entity itself.

**Comment by GeoffFroh** [comment]
see: https://github.com/densho/ddr-local/issues/252

**Comment by gjost** [comment]
Completed as of  commit 090facf and commit ae0b8b5 in ddr-cmdln.
