### ISSUE TITLE
Delete entities

### ISSUE THREAD

**Issue by GeoffFroh** [densho/ddr-local#252]
Complete the functionality to delete entities.

**Comment by gjost** [comment]
Completed as of  commit 090facf and commit ae0b8b5 in ddr-cmdln.

**Comment by pkikawa** [comment]
getting a type error deleting child entities, `delete() takes at most 5 arguments (6 given)` via web ui on MA280 (fresh update)

[TypeError at _ui_entity_ddr-testing-40211-1-4_delete_.txt](https://github.com/densho/ddr-local/files/3075354/TypeError.at._ui_entity_ddr-testing-40211-1-4_delete_.txt)

**Comment by gjost** [comment]
Should be fixed as of ddr-cmdln commit 526050bdf7 (2019-04-09).
