### ISSUE TITLE
navigating to child segment via webui refreshes page

### ISSUE THREAD

**Issue by pkikawa** [densho/ddr-local#257]
clicking on the child segment link does not navigate to the page, rather refreshes the children list page. 

tested in ver 284aDEV

**Comment by GeoffFroh** [comment]
related to earlier issue regarding edit and delete links for binaries. Result of template syntax error; probably related to `Pagination.object`

**Comment by gjost** [comment]
Fixed in ddr-local commit 6a00183 for package ddrlocal-develop_v2.8.4b.

**Comment by pkikawa** [comment]
resolved in 284b dev

**Comment by pkikawa** [comment]
working 286MA
