### ISSUE TITLE
collection creation error

### ISSUE THREAD

**Issue by pkikawa** [densho/ddr-local#269]
clicking on new collection throws this failure message, though the collection is successfully created and is listed in thew webui. 
[collection_creation.zip](https://github.com/densho/ddr-local/files/3894175/collection_creation.zip)

4.0.0-rc1 entiat

**Comment by pkikawa** [comment]
getting the same message when editing collection

**Comment by gjost** [comment]
This happens when using the current DDR with an old Elasticsearch server e.g. 2.4.  I can't fix having the wrong server but `ddr-local` commit `9d16e3d` for package `ddrlocal-rc_4.0.0-rc3~deb9` should catch the `RequestErrors` so the program doesn't crash.  Records in the local Elasticsearch will not be updated of course.

**Comment by pkikawa** [comment]
error when creating collection
RequestError(400, u'invalid_type_name_exception', {u'status': 400, u'error': {u'root_cause': [{u'reason': u"Document mapping type name can't start with '_'", u'type': u'invalid_type_name_exception'}], u'type': u'invalid_type_name_exception', u'reason': u"Document mapping type name can't start with '_'"}})

**Comment by pkikawa** [comment]
rc3

**Comment by gjost** [comment]
> rc3

What does this mean?

**Comment by sarabeckman** [comment]
We're seeing this error in ddrlocal-rc_4.0.0-rc3~deb9 package

**Comment by gjost** [comment]
I set up a fresh VM, installed `ddrlocal-rc_4.0.0-rc3~deb9_amd64.deb` on it, pointed it at another VM that's running Elasticsearch 7, and was able to successfully create a collection.  **DDR no longer works with Elasticsearch 2.4**

**Comment by GeoffFroh** [comment]
Turns out to be configuration issue.
