### ISSUE TITLE
RequestError when setting Signatures

### ISSUE THREAD

**Issue by sarabeckman** [densho/ddr-local#271]
When trying to set signature for either an object or the the collection in ddrlocal-rc_4.0.0-rc3~deb9.  I get a Request Error in the git status but the signature does get set.  

RequestError(400, u'invalid_type_name_exception', {u'status': 400, u'error': {u'root_cause': [{u'reason': u"Document mapping type name can't start with '_'", u'type': u'invalid_type_name_exception'}], u'type': u'invalid_type_name_exception', u'reason': u"Document mapping type name can't start with '_'"}})

**Comment by gjost** [comment]
I set up a fresh Debian 9 VM, installed `ddrlocal-rc_4.0.0-rc3~deb9_amd64.deb` on it, pointed it at another VM that's running Elasticsearch 7, and was able to successfully set collection and entity signatures. **NOTE: DDR no longer works with Elasticsearch 2.4**
