### ISSUE TITLE
Gitstatus returns failure for sync with RequestError result

### ISSUE THREAD

**Issue by sarabeckman** [densho/ddr-local#273]
I synced ddr-pc-50 in the Editor UI running  version 4.0.0 master ddrlocal package and the gitstatus celery message returned Failure. The result message reads :

RequestError(400, u'invalid_type_name_exception', {u'status': 400, u'error': {u'root_cause': [{u'reason': u"Document mapping type name can't start with '_'", u'type': u'invalid_type_name_exception'}], u'type': u'invalid_type_name_exception', u'reason': u"Document mapping type name can't start with '_'"}})
--

I ran `git status` in command line for `ddr-pc-50` and the collection had synced the commits I had made via Editor UI.

**Comment by GeoffFroh** [comment]
Just added important label -- this is a production issue. 

Collections can be synced from the command-line, however.

**Comment by pkikawa** [comment]
tested syncing with ES disabled and got the same message

**Comment by pkikawa** [comment]
interestingly i get thrown to a full on error page (same message) if i do the following:
dump reddis
rebot
sign in
edit collection
enable gitstatus notifications immediately after clicking edit

[Uploading TypeError at _ui_collection_ddr-testing-40299_.zip…]()

**Comment by gjost** [comment]
There's no file in that TypeError .zip

**Comment by pkikawa** [comment]
gah

[TypeError at _ui_collection_ddr-testing-40299_.zip](https://github.com/densho/ddr-local/files/3933572/TypeError.at._ui_collection_ddr-testing-40299_.zip)

**Comment by pkikawa** [comment]
its the same error as before

**Comment by GeoffFroh** [comment]
Turned out to be configuration issue
