### ISSUE TITLE
Consolidate common local controlled vocabs for Collections, Entities, and Files

### ISSUE THREAD

**Issue by GeoffFroh** [densho/ddr-local#70]
Collections, Entities and Files have several controlled vocabularies that are shared.

* STATUS_CHOICES
* LANGUAGE_CHOICES
* PERMISSIONS_CHOICES
* GENRE_CHOICES

And we will be adding rights-related CVs as well.

These CVs should be managed from a central location. Some abstraction might also make it easier to replace a local static CV with a remote CV later.

**Comment by gjost** [comment]
These now reside in the `ddr` repository on each Store, along with the model fields.
